// Generated by `pnpm gen:chains`
export {
  // RISE chain
  riseTestnet,
  // Upstream chains
  arbitrum,
  arbitrumSepolia,
  base,
  baseSepolia,
  berachain,
  berachainBepolia,
  bsc,
  celo,
  gnosis,
  hoodi,
  katana,
  mainnet,
  optimism,
  optimismSepolia,
  polygon,
  sepolia,
} from 'viem/chains'
